### ISSUE TITLE
HTTP error 500 for any API call

### ISSUE THREAD

**Issue by karaluh** [prestix-studio/cloudns_api#7] opened 2020-07-22 09:32 UTC
I just started to using the module but no matter what API call I execute I 'm always getting error 500.
The code:
```python
import cloudns_api
response = cloudns_api.api.get_login()
print(response)
```
The output:
```
{"status_code": 500, "success": false, "payload": {}, "error": "Something went wrong."}
```

**Comment by hbradleyiii** [comment] 2020-08-29 16:08
@karaluh a 500 error code is an HTTP server error. It sounds like it might be a problem that ClouDNS was having. Did you try this on more than one occasion? Do you get the same error when trying the API with curl?

Can you try this replacing <your-auth-id> and <your-password> as appropriate:
`$ curl "https://api.cloudns.net/dns/login.json?auth-id=<your-auth-id>&auth-password=<your-password>"`

**Comment by hbradleyiii** [comment] 2021-05-17 21:20
Closing this for now. I can't reproduce this. Feel free to re-open this with more info.

**Closed by hbradleyiii** 2021-05-17 21:20 UTC
